version: '3.9'

services:
  redis:
    container_name: redis
    image: redis:7
    restart: always
    ports:
      - "6379:6379"
    networks:
      - ws

  web:
    container_name: web
    build: .
    command: sh /app/scripts/run.sh
    env_file:
      - ./envs/.env.prod
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.prod
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    networks:
      - ws

volumes:
  postgres_data:

networks:
  ws:
    driver: bridge